### PR TITLE
fix: `pnpm` dependencies

### PR DESCRIPTION
**Pull request by afonsojramos**
Had to manually add these dependencies after choosing `pnpm`. Furthermore, I've faced this issue afterwards, that I'm not 100% where it is coming from.

image

### CODE REVIEW

**Comment by cpojer** [comment]
Ah, I think the problem might be that you are using `resolution-mode=lowest-direct`, which is the new default in pnpm 8: https://pnpm.io/npmrc#resolution-mode

I should probably publish a new patch release version of remdx to avoid this issue from happening. For now, do you mind trying `resolution-mode=highest` in your `.npmrc` instead of making this change?

(I'll close the PR as it is not the correct fix, but let's keep discussing here until we resolve your issue)

**Comment by afonsojramos** [comment]
Sounds good! Sorry for the useless PR then 😅

**Comment by afonsojramos** [comment]
Setting `resolution-mode=highest` in the .npmrc didn't seem to solve the issue though. Still getting the missing packages.

**Comment by cpojer** [comment]
How did you run create-remdx? If it's with npx, you have to check out your .npm cache folder and get rid of it first.

**Comment by afonsojramos** [comment]
@cpojer I used the default `npm init remdx`, and then chose pnpm. Normally this isn't an issue 😅

**Pull request closed without merging**
